### ISSUE TITLE
Not possible to keep cases in preprocess

### ISSUE THREAD

**Issue by jakob-r** [wrathematics/ngram#5]
According to the documentation this should work:
```r
ngram::preprocess("Keep Case", case = NULL)
```
But `ngram:::check.is.string` does not allow NULLs.

Small tip: Instead of writing the check functions yourself you could use [checkmate](https://github.com/mllg/checkmate) where it simply would be `assertString(remove.punct, null.ok = TRUE)`

**Comment by wrathematics** [comment]
Thanks, should be fixed now.

**Comment by jakob-r** [comment]
Thanks
