### ISSUE TITLE
Results from get.string() 

### ISSUE THREAD

**Issue by russey** [wrathematics/ngram#9]
This may be my misunderstanding, but the documentation for `get.string()` states it "recovers the input string as an R string". This would lead me to believe it should work something like this:

```
> ng <- ngram("hello", n = 1)
> get.string(ng)
[1] "hello"
```

Whereas the actual result
```
> ng <- ngram("hello", n = 1)
> get.string(ng)
[1] "p"
```

Apologies if this is working as intended.
 
Many thanks
Joe

**Comment by wrathematics** [comment]
Thanks for reporting this. It should be fixed in the latest commit.
